<a href="https://colab.research.google.com/github/subhu6371/apnacollege-demo/blob/main/basicnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d.shape)

(2, 3)


In [1]:
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d.size)

6


In [4]:
import numpy as np
arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3d.ndim)

3


.dtype returns the datatype

.dtype returns the data type(if any one float number is stored in the array then the datatype will be float

In [5]:
import numpy as np
arr=np.array([1.2,3.2,4.8])
int_arr=arr.astype(int)
print(int_arr)
print(int_arr.dtype)

[1 3 4]
int64


In [10]:
import numpy as np
arr_op=np.array([10,20,30])
print(arr_op+ 5)
print(arr_op*2)
print(arr_op**2)

[15 25 35]
[20 40 60]
[100 400 900]


AGGREGATION FUNCTION

In [12]:
import numpy as np
arr_op=np.array([10,20,30])
print(np.sum(arr_op))
print(np.min(arr_op))
print(np.max(arr_op))
print(np.mean(arr_op))
print(np.median(arr_op))

60
10
30
20.0
20.0


INDEXING AND SLICING