<a href="https://colab.research.google.com/github/subhu6371/apnacollege-demo/blob/main/basicnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d.shape)

(2, 3)


In [ ]:
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d.size)

6


In [ ]:
import numpy as np
arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3d.ndim)

3


.dtype returns the datatype

.dtype returns the data type(if any one float number is stored in the array then the datatype will be float

In [ ]:
import numpy as np
arr=np.array([1.2,3.2,4.8])
int_arr=arr.astype(int)
print(int_arr)
print(int_arr.dtype)

[1 3 4]
int64


In [ ]:
import numpy as np
arr_op=np.array([10,20,30])
print(arr_op+ 5)
print(arr_op*2)
print(arr_op**2)

[15 25 35]
[20 40 60]
[100 400 900]


AGGREGATION FUNCTION

In [ ]:
import numpy as np
arr_op=np.array([10,20,30])
print(np.sum(arr_op))
print(np.min(arr_op))
print(np.max(arr_op))
print(np.mean(arr_op))
print(np.median(arr_op))

60
10
30
20.0
20.0


INDEXING AND SLICING

In [ ]:
import numpy as np
arrind=np.array([10,20,30,40,50])
print(arrind[2])
print(arrind[2:4])

30
[30 40]


In [ ]:
#slicing
#array[start:stop:step]
#array[start:end]
import numpy as np
arrsli=np.array([10,20,30,40,50,60])
print(arrsli[1:4:2])
print(arrsli[1:4])
print(arrsli[2:])
print(arrind[::-1])
print(arrsli[:4])
print(arrind[::2])

[20 40]
[20 30 40]
[30 40 50 60]
[50 40 30 20 10]
[10 20 30 40]
[10 30 50]


In [ ]:
#fancy indexing
import numpy as np
arrsli=np.array([10,20,30,40,50,60])
print(arrsli[[1,4,2]])

[20 50 30]


In [ ]:
#boolean masking
import numpy as np
arrsli=np.array([10,20,30,40,50,60])
print(arrsli[arrsli>30])

[40 50 60]


# RESHAPING AND MANIPULATING ARRAYS

In [ ]:
#reshape(x.reshape(row,column))
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
rsarr=np.array([10,20,30,40,50,60])
print(rsarr.reshape(2,3))

[[10 20 30]
 [40 50 60]]


In [ ]:
""".ravel()-->view
   .flatten()-->copy
"""
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d.ravel())
print(arr_2d.flatten())


[1 2 3 4 5 6]
[1 2 3 4 5 6]


## ARRAY MODIFICATION

In [ ]:
"""
np.insert(array,index,value,axis=none)
array-original array
index-
value-
axis-
axis=0-->row
axis=1-->column

"""
import numpy as np
arrin=np.array([10,20,30,40,50,60])
new_arr=np.insert(arrin,2,70)
print(new_arr)

[10 20 70 30 40 50 60]


In [ ]:
#for 2d
import numpy as np
arr2d=np.array([[1,2],[3,4]])
newarr2d=np.insert(arr2d,1,[5,6],axis=0)
print(newarr2d)

[[1 2]
 [5 6]
 [3 4]]


In [ ]:
#APPEND add at last
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6]])
new_arr=np.append(arr_2d,[[7,8,9]],axis=0)
print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#concatenate add two element
"""
np.concatenate((array1,array2,array3),axis=0)

"""
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr_con=np.concatenate((arr1,arr2,arr3))
print(arr_con)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#removing array
"""np.delete(array,index,axis=none)
array-original array
index-
axis-
"""
import numpy as np
arr_del=np.array([10,20,30,40,50,60])
new_arr=np.delete(arr_del,2)
print(new_arr)

[10 20 40 50 60]


In [ ]:
import numpy as np
arr_del=np.array([[1,2,3],[4,5,6]])
new_arr=np.delete(arr_del,1,axis=0)
print(new_arr)

[[1 2 3]]


In [ ]:
#stacking
"""
vstack()  vertically
hstack()  horizontally
column_stack()
row_stack()
"""
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
#spliting
"""
np.split(()->equal
np.vsplit(()->
np.hsplit(()->
"""
import numpy as np
arr_spl=np.array([1,2,3,4,5,6])
new_arr=np.split(arr_spl,3)
print(new_arr)


[array([1, 2]), array([3, 4]), array([5, 6])]


## BROADCASTING AND VECTORIZATION

In [ ]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6]])
vector=np.array([10,20,30])
result=matrix+vector
print(result)

[[11 22 33]
 [14 25 36]]


In [ ]:
#vectorization
import numpy as np
arrvn=np.array([[1,2,3],[4,5,6]])
print(arrvn*2)
print(arrvn+5)

[[ 2  4  6]
 [ 8 10 12]]
[[ 6  7  8]
 [ 9 10 11]]


HANDLING MISSING VALUES

In [ ]:
import numpy as np
arrmis=np.array([1,2,np.nan,4,5,np.nan])
print(np.isnan(arrmis))

[False False  True False False  True]


In [ ]:
#np.nan_to_num(arr)/(arr,nan=value)
import numpy as np
arrmis=np.array([1,2,np.nan,4,5,np.nan])
print(np.nan_to_num(arrmis))



[1. 2. 0. 4. 5. 0.]


In [ ]:
#np.isinf(arr)
#np.nan_to_num(arr,posinf=v,neginf=v)
import numpy as np
arrinf=np.array([1,2,np.inf,4,-np.inf])
print(np.isinf(arrinf))
val_arr=np.nan_to_num(arrinf,posinf=10,neginf=-11)
print(val_arr)

[False False  True False  True]
[  1.   2.  10.   4. -11.]


In [ ]:


| ID | Name    | Age | Gender | Department | Salary | Join Date  | Performance Score |
| -- | ------- | --- | ------ | ---------- | ------ | ---------- | ----------------- |
| 1  | Alice   | 25  | F      | HR         | 50000  | 2020-01-15 | 85                |
| 2  | Bob     | 30  | M      | IT         | 70000  | 2019-08-01 | 90                |
| 3  | Charlie | 28  | M      | Finance    | 65000  | 2021-06-23 | 75                |
| 4  | Diana   | 35  | F      | IT         | 72000  | 2018-11-05 | 88                |
| 5  | Ethan   | 24  | M      | HR         | 48000  | 2022-03-12 | 70                |
| 6  | Fiona   | 29  | F      | Finance    | 62000  | 2020-09-30 | 95                |
| 7  | George  | 31  | M      | IT         | 71000  | 2017-04-18 | 82                |
| 8  | Hannah  | 27  | F      | HR         | 51000  | 2019-07-09 | 77                |
