<a href="https://colab.research.google.com/github/subhu6371/apnacollege-demo/blob/main/googlecollab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd

# Create a simple DataFrame (table of data)
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
}

df = pd.DataFrame(data)

# Show the data
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


**bold text**# New Section

In [1]:
import numpy as np

# Create two 2x2 arrays
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Element-wise addition
C = A + B

# Element-wise multiplication
D = A * B

# Matrix multiplication
E = np.dot(A, B)

# Print results
print("Element-wise Addition:\n", C)
print("Element-wise Multiplication:\n", D)
print("Matrix Multiplication:\n", E)

Element-wise Addition:
 [[ 6  8]
 [10 12]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


# New Section